controller_list:
  - name: pos_joint_trajectory_controller
    type: position_controllers/JointPositionController
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
  - name: franka_gripper
    action_ns: gripper_action
    type: GripperCommand
    joints:
      - panda_finger_joint1
      - panda_finger_joint2
